//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMst
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string TaxNo { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public string PANNo { get; set; }
        public string Country { get; set; }
    }
}
