//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurInvoiceDet
    {
        public long InvDetId { get; set; }
        public Nullable<int> InvId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> ItemDiscountPer { get; set; }
        public Nullable<decimal> ItemDiscountAmt { get; set; }
        public Nullable<int> ItemTaxId { get; set; }
        public Nullable<decimal> TaxableAmt { get; set; }
        public Nullable<decimal> ItemIGstPer { get; set; }
        public Nullable<decimal> ItemIGstAmt { get; set; }
        public Nullable<decimal> ItemCGstPer { get; set; }
        public Nullable<decimal> ItemCGstAmt { get; set; }
        public Nullable<decimal> ItemSGstPer { get; set; }
        public Nullable<decimal> ItemSGstAmt { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
    }
}
