//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptMst
    {
        public Nullable<int> ReceiptNo { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Mode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CashBankId { get; set; }
        public Nullable<decimal> ReceiptAmt { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public Nullable<decimal> ReceivedAmt { get; set; }
        public int ReceiptId { get; set; }
    }
}
